/**:
  ros__parameters:
    window_length: 0.5                            # [sec]
    comparison_target: "odometry"     # select from "pose_with_covariance" or "odometry"

    output_x_y_yaw_only: true                     # true/false

    heading_velocity_maximum: 2.778               # [m/s]
    heading_velocity_scale_factor_tolerance: 3.0  # [%]

    angular_velocity_maximum: 0.523               # [rad/s]
    angular_velocity_scale_factor_tolerance: 0.2  # [%]
    angular_velocity_bias_tolerance: 0.00698      # [rad/s]

    pose_estimator_longitudinal_tolerance: 0.11   # [m]
    pose_estimator_lateral_tolerance: 0.11        # [m]
    pose_estimator_vertical_tolerance: 0.11       # [m]
    pose_estimator_angular_tolerance: 0.0175      # [rad]
