/**:
  ros__parameters:
    filter_names: ["autoware::trajectory_traffic_rule_filter::plugin::TrafficLightFilter"]
    debug_mode: true # when true, all trajectories are always accepted but the diagnostics are accurately published
    traffic_light_filter:
      deceleration_limit: 2.8
      jerk_limit: 5.0
      delay_response_time: 0.5
      crossing_time_limit: 2.75
      treat_amber_light_as_red_light: true
